[package]
name = "pijul"
version = "0.1.0"
authors = ["Pierre-Ã‰tienne Meunier","Florent Becker"]
build="build.rs"

[dependencies]
libc = "0.1.0"
clap = "1.4.5"
rand="0.3"
[build-dependencies]
gcc="0.3.19"